### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by ishanvaghani** [Amitbhave/flutter-simple-url-preview#16]
This package is not migrated to null safe. when it will done?

**Comment by Amitbhave** [comment]
@ishanvaghani unfortunately this package currently uses flutter_cache_store package, which is not yet migrated to null-safety. I have created this issue: https://github.com/eGust/flutter_cache_store/issues/21
I will wait for a couple of weeks for that package owner to migrate to null-safety, otherwise will have to look for other option for caching the URL response and then will have to migrate to null-safety.

**Comment by imrhk** [comment]
Is it possible that you change the dependency of flutter_cache_store to dio-http-cache?

**Comment by Amitbhave** [comment]
@imrhk , sure will have to look into alternatives for flutter_cache_store..

**Comment by sajanyamaha** [comment]
dont think flutter_cache_store is going to migrate , your request is closed there without any resolution .

**Comment by Amitbhave** [comment]
Yes, I will use some other option for caching and then migrate this to null safety as soon as possible now. Don't think flutter_cache_store will be migrated to null safety anytime soon..

**Comment by iqfareez** [comment]
Following this issue. Hoping to see this package migrated to null safety. 😄

**Comment by Amitbhave** [comment]
@iqfareez, soon :)

**Comment by Amitbhave** [comment]
Apologies for taking so long. Finally, the package is migrated to null safety.
Use version 3.0.1
Special thanks to @vinothvino42 for helping me to get this done!
Thanks all for your support!
