### ISSUE TITLE
Cache network requests

### ISSUE THREAD

**Issue by paurakhsharma** [Amitbhave/flutter-simple-url-preview#6]
We need to show users a list of `SimpleUrlPreview()`,  so, every time the user goes to this page
the app needs to reload all those `SimpleUrlPreview()`.

So, I was thinking about caching the response from the URL so that it doesn't take a long time when the user goes to the page for the next time.

I am aware all the users of the package might not need to display the list of `SimpleUrlPreview()` so, you might not want to implement this in this package. 

Please let me know if you are willing to add this feature in the package if so I will be happy to create a PR.
Else, I want to fork this package and add that functionality. I am thinking about using `shared_preferences`
for this. Please let me know if you have any better suggestions.

Thanks.

**Comment by paurakhsharma** [comment]
I also thought of extending the class to override `_getUrlData()` but I guess I cannot do that because it is a `private` method.

**Comment by Amitbhave** [comment]
@paurakhsharma rather than using SharedPrefs, I used the [flutter_cache_store](https://pub.dev/packages/flutter_cache_store) package to cache the HTTP response which by default uses LessRecentlyUsed strategy for caching. If we use SharedPrefs directly, we will have to also take care of eviting the keys.
Version 1.1.0 has been released. Let me know your feedback on the same, and we can close this issue.

**Comment by paurakhsharma** [comment]
Thank you so much, this is way better 🙂

**Comment by paurakhsharma** [comment]
@Amitbhave I just realized it is somewhat slower than ShardPrefs, but it is better than having nothing.

**Comment by Amitbhave** [comment]
True @paurakhsharma ! Only problem was those key wouldn't get evicted for SharedPrefs option..
